### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by Macarse** [apportable/Foundation#1]
When calling: ndk-build 

 Android NDK: ERROR:/path/Foundation/jni/Android.mk:objc: LOCAL_SRC_FILES points to a missing file  
 Android NDK: Check that /path/Foundation/jni/libobjc.so exists  or that its path is correct  
 /path/android-ndk-r7/build/core/prebuilt-library.mk:43: **\* Android NDK: Aborting    .  Stop.

Also I noticed that folders inside foundation are symbolic links, for example:
CoreFoundation -> ../../../../CoreFoundation

where should they point to?

**Comment by sakrist** [comment]
for android-ndk-r8d
~/android-ndk-r8d/build/gmsl/__gmsl:512: **\* non-numeric second argument to `wordlist' function: ''.  Stop.

**Comment by paulb777** [comment]
Bug report on GNUstep based version of Foundation. We're now using a CFLite based Foundation that uses Xcode as its build system.
